/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.14
 * Generated at: 2022-02-04 16:20:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Date;
import java.util.TimeZone;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Calendar;

public final class customerform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/css/include_css.jsp", Long.valueOf(1641934371693L));
    _jspx_dependants.put("/global/footer.jsp", Long.valueOf(1641935962649L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1641934371688L));
    _jspx_dependants.put("/WEB-INF/css/starter-template.css", Long.valueOf(1642539876457L));
    _jspx_dependants.put("/p2/global/header.jsp", Long.valueOf(1641934371697L));
    _jspx_dependants.put("/global/header.jsp", Long.valueOf(1641935972873L));
    _jspx_dependants.put("/a5/global/header.jsp", Long.valueOf(1641934371692L));
    _jspx_dependants.put("/WEB-INF/css/formValidation.min.css", Long.valueOf(1641934371660L));
    _jspx_dependants.put("/a4/global/header.jsp", Long.valueOf(1641934371692L));
    _jspx_dependants.put("/global/nav_global.jsp", Long.valueOf(1643141865826L));
    _jspx_dependants.put("jar:file:/usr/local/var/tomcat/webapps/lis4368/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602888372000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.GregorianCalendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.TimeZone");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!--\r\n");
      out.write("\"Time-stamp: <Sat, 12-19-20, 17:48:53 Eastern Standard Time>\"\r\n");
      out.write("//-->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<meta name=\"description\" content=\"My online portfolio that illustrates skills acquired while working through various project requirements.\">\r\n");
      out.write("	<meta name=\"author\" content=\"Mark K. Jowett, Ph.D.\">\r\n");
      out.write("	<link rel=\"icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("	<title>CRSXXXX - JSP Forms</title>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<!-- Include FontAwesome CSS to use feedback icons provided by FontAwesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("Bootstrap Integrity and Crossorigin attributes:\r\n");
      out.write("http://stackoverflow.com/questions/32039568/what-are-the-integrity-and-crossorigin-attribute\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap for responsive, mobile-first design. -->\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("	<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("	<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Starter template for your own custom styling. -->\r\n");
      out.write("<!-- https://stackoverflow.com/questions/7382607/how-to-load-css-file-into-jsp -->\r\n");
      out.write("<style>");
      out.write("body\n");
      out.write("{\n");
      out.write("  padding-top: 50px;\n");
      out.write("}\n");
      out.write(".starter-template\n");
      out.write("{\n");
      out.write("  padding: 0px 15px;\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("h1\n");
      out.write("{\n");
      out.write("	margin: 0px;\n");
      out.write("	color: #000;\n");
      out.write("	padding: 0px;\n");
      out.write("	font-size: 36px;\n");
      out.write("	font-family: \"trebuchet ms\", sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar {\n");
      out.write("  .navbar-inner {\n");
      out.write("    background-color: #2c2c2c;\n");
      out.write("    background-image: none;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Form validation styling. -->\r\n");
      out.write("<style>");
      out.write(".fv-has-feedback{position:relative}.fv-control-feedback{position:absolute;top:0;right:0;z-index:2;display:block;width:34px;height:34px;line-height:34px;text-align:center}.fv-help-block{display:block}.fv-form-bootstrap .help-block{margin-bottom:0}.fv-form-bootstrap .tooltip-inner{text-align:left}.fv-form-bootstrap .fv-icon-no-label{top:0}.fv-form-bootstrap .fv-bootstrap-icon-input-group{z-index:100}.form-inline.fv-form-bootstrap .form-group{vertical-align:top}.fv-form-foundation .fv-control-feedback{top:21px;right:15px;width:37px;height:37px;line-height:37px}.fv-form-foundation .collapse .fv-control-feedback{top:0;right:0}.fv-form-foundation .fv-icon-no-label,.fv-form-horizontal.fv-form-foundation .fv-control-feedback{top:0}.fv-form-foundation .error .fv-control-feedback{color:#f04124}.error.fv-has-tooltip select,.error.fv-has-tooltip textarea,.fv-form-foundation .error.fv-has-tooltip input{margin-bottom:1rem}.fv-form-pure .fv-control-feedback{top:22px;width:36px;height:36px;line-height:36px}.pure-form-stacked.fv-form-pure .fv-control-feedback{top:4px}.pure-form-aligned .pure-control-group .fv-help-block{margin-top:5px;margin-left:180px}.fv-form-pure .fv-icon-no-label,.pure-form-aligned.fv-form-pure .fv-control-feedback{top:0}.fv-form-pure .fv-has-error .fv-control-feedback,.fv-form-pure .fv-has-error .fv-help-block,.fv-form-pure .fv-has-error label{color:#CA3C3C}.fv-form-semantic .fv-control-feedback.icon{right:7px}.fv-form-semantic .error .icon{color:#d95c5c}.fv-form-horizontal.fv-form-semantic .row{padding-bottom:0}.fv-form-uikit .fv-control-feedback{top:25px;width:30px;height:30px;line-height:30px}.fv-form-uikit .uk-text-danger{display:block}.uk-form-horizontal.fv-form-uikit .fv-control-feedback{top:0}.fv-form-uikit .fv-has-error .fv-control-feedback,.fv-form-uikit .fv-has-error .uk-form-label,.fv-form-uikit .fv-has-error label{color:#D85030}.fv-form-uikit .fv-icon-no-label{top:0}");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery DataTables: http://www.datatables.net/ //-->\r\n");
      out.write("<!-- jQuery DataTables CDN: https://cdn.datatables.net/ //-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/v/dt/dt-1.10.16/r-2.2.1/datatables.min.css\"/>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- display application path -->\r\n");
 //= request.getContextPath()
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!-- can also find path like this...<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'/a5/index.jsp'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">A5</a> -->	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-light navbar-fixed-top color\" style=\"background: #FFDAB9;\" >\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("					<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("					<span class=\"icon-bar\"></span>\r\n");
      out.write("					<span class=\"icon-bar\"></span>\r\n");
      out.write("					<span class=\"icon-bar\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\" target=\"_self\">Home</a>\r\n");
      out.write("			</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"navbar\" class=\"collapse navbar-collapse\">\r\n");
      out.write("				<ul class=\"nav navbar-nav\">\r\n");
      out.write("					<li><a href=\"index.jsp\">LIS4368</a></li>\r\n");
      out.write("					<li><a href=\"a1/index.jsp\">A1</a></li>\r\n");
      out.write("					<li><a href=\"a2/index.jsp\">A2</a></li>\r\n");
      out.write("					<li><a href=\"a3/index.jsp\">A3</a></li>\r\n");
      out.write("					<li><a href=\"customerform.jsp?assign_num=a4\">A4</a></li>\r\n");
      out.write("					<li><a href=\"customerform.jsp?assign_num=a5\">A5</a></li>\r\n");
      out.write("					<li><a href=\"p1/index.jsp\">P1</a></li>\r\n");
      out.write("					<li><a href=\"customerform.jsp?assign_num=p2\">P2</a></li>\r\n");
      out.write("					<li><a href=\"customerform.jsp?assign_num=test\">Test</a></li>\r\n");
      out.write("					<li><a href=\"../hello/sayhello\">Hello Home</a></li>\r\n");
      out.write("					<li><a href=\"../hello/querybook.html\">Query Book</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div><!--/.nav-collapse -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");

//https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html
SimpleDateFormat timeFormat = new SimpleDateFormat("M/d/yy h:m a ");
timeFormat.setTimeZone(TimeZone.getTimeZone("America/New_York"));
String time = timeFormat.format(new Date());

      out.write('\r');
      out.write('\n');
      out.print( time );
      out.write('\r');
      out.write('\n');
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"starter-template\">\r\n");
      out.write("					<div class=\"page-header\">\r\n");
      out.write("\r\n");
      out.write("					<!-- View source or uncomment to display Parameter value...\r\n");
      out.write("								Parameter value: ");
      out.print( request.getParameter("assign_num") );
      out.write("\r\n");
      out.write("\r\n");
      out.write("								Note: use JSTL (JSP Standard Tag Library) combined with EL (Expression Language), instead of Java scriplets to run conditional logic.\r\n");
      out.write("								To use core tag must include tag Library link in first line of file - see top.\r\n");
      out.write("								");
  //@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" 
      out.write("\r\n");
      out.write("								Also, need taglib .jar files. See WEB-INF > lib directory.\r\n");
      out.write("						-->\r\n");
      out.write("\r\n");
      out.write("					");
  // w/o using taglib: String anum = request.getParameter("assign_num"); 
      out.write("\r\n");
      out.write("					<!-- Or, using JSTL's expression language (EL): request parameters made available in implicit param object. -->\r\n");
      out.write("						\r\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<!-- Uncomment to Print: -->\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\r\n");
            out.write("						");
            if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\r\n");
            out.write("						");
            if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\r\n");
            out.write("						");
            if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("						\r\n");
            out.write("						");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("							");
 response.sendRedirect("/lis4368/index.jsp"); 
                  out.write("\r\n");
                  out.write("						");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<!--\r\n");
      out.write("							 https://www.tutorialspoint.com/servlets/servlets-first-example.htm								\r\n");
      out.write("							 http://stackoverflow.com/questions/11731377/servlet-returns-http-status-404-the-requested-resource-servlet-is-not-availa								\r\n");
      out.write("							 Form action submission to URL with leading slash:\r\n");
      out.write("							 <form action=\"/servlet\">\r\n");
      out.write("							 Leading slash / makes URL relative to domain, that is, form will submit to:\r\n");
      out.write("							 http://localhost:9999/servlet\r\n");
      out.write("\r\n");
      out.write("							 Form action submission to URL w/o leading slash:								\r\n");
      out.write("							 <form action=\"servlet\">\r\n");
      out.write("							 Makes URL relative to current directory of current URL. Form will submit to:\r\n");
      out.write("							 http://localhost:9999/contextname/somedirectory/servlet								\r\n");
      out.write("\r\n");
      out.write("							 Best solution: make URL domain-relative (won't need to fix URLs when JSP/HTML files moved into another folder)\r\n");
      out.write("							 <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/servlet\">\r\n");
      out.write("\r\n");
      out.write("							 Makes URL context relative. Form will submit to:								\r\n");
      out.write("							 <form action=\"/contextname/servlet\">\r\n");
      out.write("							 Will *always* submit to correct URL!\r\n");
      out.write("\r\n");
      out.write("							 Use this servlet for testing: ShowParameters								\r\n");
      out.write("					-->\r\n");
      out.write("					\r\n");
      out.write("					<p><a href=\"customerAdmin?action=display_customers\">Display Customers</a></p>\r\n");
      out.write("\r\n");
      out.write("					");
 //for debugging, test input (test servlet provided): action="testInput" 
      out.write("\r\n");
      out.write("					<form id=\"add_customer_form\" method=\"post\" class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customerAdmin\">\r\n");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"action\" value=\"add_customer\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"col-sm-4 control-label\">FName:</label>\r\n");
      out.write("							<div class=\"col-sm-4\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" maxlength=\"15\" name=\"fname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.fname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"col-sm-4 control-label\">LName:</label>\r\n");
      out.write("							<div class=\"col-sm-4\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" maxlength=\"30\" name=\"lname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.lname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"col-sm-4 control-label\">Email:</label>\r\n");
      out.write("							<div class=\"col-sm-4\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" maxlength=\"100\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\" name=\"signup\" value=\"Sign up\">Submit</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("					");
      out.write("<br />\r\n");
      out.write("\r\n");

    GregorianCalendar currentDate = new GregorianCalendar();
    int currentYear = currentDate.get(Calendar.YEAR);

      out.write("\r\n");
      out.write("&copy; Copyright ");
      out.print( 2022 );
      out.write(" Sarah Huerta, Inc.\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div> <!-- end starter-template -->\r\n");
      out.write("	</div> <!-- end container -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write(" 	");
      out.write("		\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("	$('#add_customer_form').formValidation({\r\n");
      out.write("			message: 'This value is not valid',\r\n");
      out.write("			icon: {\r\n");
      out.write("					valid: 'fa fa-check',\r\n");
      out.write("					invalid: 'fa fa-times',\r\n");
      out.write("					validating: 'fa fa-refresh'\r\n");
      out.write("			},\r\n");
      out.write("			fields: {\r\n");
      out.write("\r\n");
      out.write("				fname: {\r\n");
      out.write("							validators: {\r\n");
      out.write("									notEmpty: {\r\n");
      out.write("											message: 'First name required'\r\n");
      out.write("									},\r\n");
      out.write("									stringLength: {\r\n");
      out.write("											min: 1,\r\n");
      out.write("											max: 15,\r\n");
      out.write("											message: 'First name no more than 15 characters'\r\n");
      out.write("									},\r\n");
      out.write("									regexp: {\r\n");
      out.write("										//http://www.regular-expressions.info/\r\n");
      out.write("										//http://www.regular-expressions.info/quickstart.html\r\n");
      out.write("										//http://www.regular-expressions.info/shorthand.html\r\n");
      out.write("										//http://stackoverflow.com/questions/13283470/regex-for-allowing-alphanumeric-and-space\r\n");
      out.write("										//alphanumeric (also, \"+\" prevents empty strings):\r\n");
      out.write("										regexp: /^[a-zA-Z\\-]+$/,\r\n");
      out.write("										message: 'First name can only contain letters and hyphens.'\r\n");
      out.write("									},									\r\n");
      out.write("							},\r\n");
      out.write("					},\r\n");
      out.write("\r\n");
      out.write("				lname: {\r\n");
      out.write("							validators: {\r\n");
      out.write("									notEmpty: {\r\n");
      out.write("											message: 'Last name required'\r\n");
      out.write("									},\r\n");
      out.write("									stringLength: {\r\n");
      out.write("											min: 1,\r\n");
      out.write("											max: 30,\r\n");
      out.write("											message: 'Last name no more than 30 characters'\r\n");
      out.write("									},\r\n");
      out.write("									regexp: {\r\n");
      out.write("										regexp: /^[a-zA-Z\\-]+$/,\r\n");
      out.write("										message: 'Last name can only contain letters and hyphens'\r\n");
      out.write("									},									\r\n");
      out.write("							},\r\n");
      out.write("					},\r\n");
      out.write("				\r\n");
      out.write("					email: {\r\n");
      out.write("							validators: {\r\n");
      out.write("									notEmpty: {\r\n");
      out.write("											message: 'Email address is required'\r\n");
      out.write("									},\r\n");
      out.write("\r\n");
      out.write("									/*\r\n");
      out.write("									//built-in e-mail validator, comes with formValidation.min.js\r\n");
      out.write("									//using regexp instead (below)\r\n");
      out.write("									emailAddress: {\r\n");
      out.write("											message: 'Must include valid email address'\r\n");
      out.write("									},\r\n");
      out.write("									*/\r\n");
      out.write("								\r\n");
      out.write("									stringLength: {\r\n");
      out.write("											min: 1,\r\n");
      out.write("											max: 100,\r\n");
      out.write("											message: 'Email no more than 100 characters'\r\n");
      out.write("									},\r\n");
      out.write("									regexp: {\r\n");
      out.write("									regexp: /^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/,\r\n");
      out.write("										message: 'Must include valid email'\r\n");
      out.write("									},																		\r\n");
      out.write("							},\r\n");
      out.write("					},\r\n");
      out.write("			}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /customerform.jsp(46,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("anum");
      // /customerform.jsp(46,5) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/customerform.jsp(46,5) '${param.assign_num}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${param.assign_num}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /customerform.jsp(46,5) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("request");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /customerform.jsp(51,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${anum == null || anum == '0'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						");
          out.write("<h1>LIS4368</h1>\r\n");
          out.write("\r\n");
          out.write("					</div>\r\n");
          out.write("					<p><i>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</i></p>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /customerform.jsp(57,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${anum == 'a4'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          out.write("<h1>Assignment 4</h1>\r\n");
          out.write("<h3>See...</h3>\r\n");
          out.write("<p class=\"lead\">...video.</p>\r\n");
          out.write("\r\n");
          out.write("(Table: customer)\r\n");
          out.write("													\r\n");
          out.write("				</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /customerform.jsp(62,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${anum == 'a5'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          out.write("<h1>Assignment 5</h1>\r\n");
          out.write("<h3>See...</h3>\r\n");
          out.write("<p class=\"lead\">...video.</p>\r\n");
          out.write("\r\n");
          out.write("(Table: customer)\r\n");
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /customerform.jsp(67,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${anum == 'p2'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          out.write("<h1>Project 2</h1>\r\n");
          out.write("<h3>See...</h3>\r\n");
          out.write("<p class=\"lead\">...video.</p>\r\n");
          out.write("\r\n");
          out.write("(Table: customer)\r\n");
          out.write("													\r\n");
          out.write("			</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }
}
